name: Continuous Delivery Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Decode Gradle Play Publisher Credentials
        id: decode_play_store_credentials
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'gradle_playstore_publisher_credentials.json'
          fileDir: './'
          encodedString: ${{ secrets.PLAYSTORE_CREDENTIALS }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Check
        run: |
          ./gradlew --console=plain :composeApp:check

  detekt:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run detekt
        run: |
          ./gradlew --console=plain detekt

      - name: Upload detekt reports
        uses: actions/upload-artifact@v3
        with:
          name: detekt
          path: build/reports/detekt/

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Run lint
        run: |
          ./gradlew --console=plain lint

      - name: Upload lint reports
        uses: actions/upload-artifact@v3
        with:
          name: lint
          path: |
            app/build/reports/lint*
            domain/build/reports/lint*
            data/build/reports/lint*

  unit_tests:
    needs: [ check ]
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Run debug unit tests
        run: |
          ./gradlew --console=plain koverXmlReportDebug --stacktrace

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tests
          path: app/build/reports/tests

      - name: Add coverage report to PR
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/app/build/reports/kover/xml/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: App Coverage
          update-comment: true
          min-coverage-overall: 20
          min-coverage-changed-files: 50

  # upload an android bundle to google play store into the internal test track
  deployment:
    needs: [ unit_tests ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Cache between builds
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Decode Android Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'android_release.keystore'
          encodedString: ${{ secrets.ANDROID_KEYSTORE }}

      - name: Decode Gradle Play Publisher Credentials
        id: decode_play_store_credentials
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'gradle_playstore_publisher_credentials.json'
          fileDir: './'
          encodedString: ${{ secrets.PLAYSTORE_CREDENTIALS }}

      - name: Build release bundle
        run: |
          ./gradlew --console=plain -PreleaseKeystore=${{ steps.decode_keystore.outputs.filePath }} -PreleaseStorePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} -PreleaseKeyAlias=${{ secrets.ANDROID_KEYSTORE_KEY_ALIAS }} -PreleaseKeyPassword=${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }} app:bundle

      - name: Publish release bundle
        run: |
          ./gradlew --console=plain composeApp:publishBundle --artifact-dir composeApp/build/outputs/bundle/release/app-release.aab
